### ISSUE TITLE
Cannot save a newly created tourament via API

### ISSUE THREAD

**Issue by sensibledon** [challonge-community/challonge-ruby-gem#1]
Hello, I'm following along the code example and I am unable to create a new tourney via the api call:

<pre>
require 'active_resource'
require 'challonge/api'
require 'challonge/tournament'
require 'challonge/participant'
require 'challonge/match'
gem 'challonge-api'

Challonge::API.username = 'my_user_name'
Challonge::API.key = 'my_api_key'
</pre>

<pre>
Challonge::Tournament.find(:all)
</pre>

- This works correctly and identifies the tournament I have created manually on the site.. score.

OK, let's try to create a new tourney now.

<pre>
t = Challonge::Tournament.new

t.name = 'Basic Single Elim Tournament rapi'
t.url = 'tourney_X'
t.tournament_type = 'single eliination'

begin
  t.save
rescue Exception => err
  $stderr.puts "RESCUE (from t.errors.full_messages):\t#{t.errors.full_messages}"
  $stderr.puts "RESCUE (from err):\t#{err}"
ensure
  $stderr.puts "Ensure...."
end
</pre>

Output:

<pre>
RESCUE (full):  []
RESCUE (full):  Failed.  Response code = 500.  Response message = Internal Server Error.
Ensure.
</pre>

So, you can see that I get a 500 response code when trying to save a new tourney using the suggested code.  Any thoughts? Let me know if you would prefer that I ask the Challonge folks instead.

Thanks!
Don

**Comment by akdarrah** [comment]
It looks like the problem with your example is there is a typo in 'single elimination' (copied from the README):

```
t.tournament_type = 'single eliination'
```

I updated the README to be correct. All you should have to do to get your example to work is change that line to:

```
t.tournament_type = 'single elimination'
```

Thanks for pointing this out!
