### ISSUE TITLE
Find a single tournament?

### ISSUE THREAD

**Issue by x3igh7** [challonge-community/challonge-ruby-gem#2]
I was wonder if there was a way to find a single tournament via the API - that is, not in an array.

Right now I am doing:

``` ruby
t = Challonge::Tournament.find(:all, :params => {:url => "url_name"})
t = t[0]
```

I would love if it were a bit cleaner and I didn't have to work off an array, by using :one or something instead of :all . Maybe there is a way to do this already and I'm missing it :)

Thanks!

**Comment by corneldm** [comment]
You can pass a URL (or id) directly to find for a single result:

``` ruby
t = Challonge::Tournament.find("url_name")
```

Though, be prepared to handle this: "ActiveResource::ResourceNotFound: Failed.  Response code = 404.  Response message = Not Found."

This gem is in dire need of a refresh, so we'll work on improving areas like this. There's a good chance that we'll abandon ActiveResource to clean up syntax. At the very least, we'll need to add OAuth2 support in preparation for v2 of the Challonge API.

**Comment by x3igh7** [comment]
Thanks! Good luck with the updates.

For the record, some other things I've noticed is you can't save the subdomain. When you do save, you can't edit via the API since there is no call for "accepting_predictions". 

Right now, if you want to add a tournament under a subdomain, it seems you can just get around this by changing it manually and using the .reload .

.publish! doesn't seem to work either.

Just figured you may like to know.
