### ISSUE TITLE
Using Challonge ARes models with Rails form helper

### ISSUE THREAD

**Issue by arielkirkwood** [challonge-community/challonge-ruby-gem#4]
Hi,

I'm trying to build a Rails application with this gem and I'm running into an issue when trying to set up a form for a Challonge model.

Here is my code so far:

``` ruby
# models/tournament.rb
class Tournament < Challonge::Tournament
end
```

The controller function I'm trying to work with at the moment:

``` ruby
# controllers/tournaments_controller.rb
class TournamentsController < ApplicationController
  def new
    @tournament = Tournament.new
  end
end
```

And the form view I generated with `rails g scaffold_controller`:

``` erb
<% # views/tournaments/_form.html.erb %>
<%= form_for(@tournament) do |f| %>
  <% if @tournament.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tournament.errors.count, "error") %> prohibited this tournament from being saved:</h2>

      <ul>
      <% @tournament.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :tournament_type %><br />
    <%= f.text_field :tournament_type %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
```

When I try to load the new tournament page, I get a `NoMethodError` from Rails, saying `undefined method 'name'`. I did a bit of research and it looks like the form helper is expecting getter and setter methods for any fields you put in your form, and the Challonge::Tournament class doesn't have these for `name` and `tournament_type`, at least. 

Curiously, it does have these methods for `description`, and as a result, Rails does not throw an error for that piece of the form. I found a way to hack around the issue by rewriting the following: 

``` ruby
# old
@tournament = Tournament.new # Tournament subclasses Challonge::Tournament

# new
@tournament = Tournament.new(:name => "", :tournament_type => "")
```

By pre-setting the values of `name` and `tournament_type` to blank strings, the form helper no longer complains about missing methods for these fields. I'm wondering if there's a better, more DRY solution to this issue, though.

As of when I wrote up this issue, I'm using Rails 3.2.16 on Ruby 2.1.2, on OS X Mavericks 10.9.2.

**Comment by corneldm** [comment]
I think this is related to us using ActiveResource in the gem. ActiveResource records have no knowledge of the remote schema, so they let you define any attributes you want (like the behavior of an OpenStruct). Until we overhaul the gem, defining blank strings for those attributes is probably your best course of action.

We're inching toward completion of API v2, and a major gem update will accompany it. That'll mean no more ActiveResource, and much friendlier patterns for Rails 3 & 4.

Until then, feel free to poke around the gem's source — there's not a lot there — and submit a pull request if there are some changes that'll make your life easier. Thanks so much!

**Comment by arielkirkwood** [comment]
Great to hear you guys are working on an update! I'm looking forward to it.
